[project]
name = "hedron_scripts"
version = "0.4.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jim McNeill" },
    { name = "Marcel Tünnissen", email = "marcelteun@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "moderngl>=5.12.0",
    "numba>=0.67.0",
    "numpy>=2.5.2",
    "pillow>=12.3.0",
    "pygame>=2.6.1",
    "scipy>=1.18.0",
    "tkinterdnd2>=0.6.2",
    "windnd>=1.0.7",
]

[project.scripts]
facetings = "offviewer.facetings:main"
offchecker = "offviewer.offchecker:main"
offviewer = "offviewer.offviewer:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.3",
]
